CREATE TABLE [dbo].[v4_4_DataElementMapping]
(
[Notes] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Section Title] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Data Element Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Sequence Number] [float] NULL,
[Short Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[SECTION_TITLE] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Data Element Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Short Name1] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Data Element Sequence] [float] NULL,
[REGISTRY_DATA_ELEMENT_ID] [float] NULL,
[Data Type] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UOM] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[IS_MULTI_SELECT] [float] NULL,
[Concept ID] [float] NULL,
[Concept Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Workflow Concept ID] [float] NULL,
[Workflow Concept Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Domain ConceptID] [float] NULL,
[Domain Concept Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[DataSource] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Coding Instruction] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[ContainmentTypeID_1 - attribute_2 - related element] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Containing Data Element ID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Schema Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Table Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Column Name] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Time Part] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[UnitConceptID] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Flip Indicator Value] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Comment] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Special Coding Instructions] [nvarchar] (max) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[Change Note] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
[F33] [nvarchar] (255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
